In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Import Data

In [4]:
customers = pd.read_csv(r'E:\datathon_2026\data\customers.csv')
geography = pd.read_csv(r'E:\datathon_2026\data\geography.csv')
inventory = pd.read_csv(r'E:\datathon_2026\data\inventory.csv')
order_items = pd.read_csv(r'E:\datathon_2026\data\order_items.csv')
orders = pd.read_csv(r'E:\datathon_2026\data\orders.csv')
payments = pd.read_csv(r'E:\datathon_2026\data\payments.csv')
products = pd.read_csv(r'E:\datathon_2026\data\products.csv')
promotions = pd.read_csv(r'E:\datathon_2026\data\promotions.csv')
returns = pd.read_csv(r'E:\datathon_2026\data\returns.csv')
reviews = pd.read_csv(r'E:\datathon_2026\data\reviews.csv')
sales = pd.read_csv(r'E:\datathon_2026\data\sales.csv')
web_traffic = pd.read_csv(r'E:\datathon_2026\data\web_traffic.csv')

# Chuyển đổi các cột ngày tháng sang định dạng datetime
orders['order_date'] = pd.to_datetime(orders['order_date'])
returns['return_date'] = pd.to_datetime(returns['return_date'])
web_traffic['date'] = pd.to_datetime(web_traffic['date'])

C:\Users\Admin\AppData\Local\Temp\ipykernel_12472\1092170212.py:4: DtypeWarning: Columns (0: promo_id_2) have mixed types. Specify dtype option on import or set low_memory=False.
  order_items = pd.read_csv(r'E:\datathon_2026\data\order_items.csv')

* Q1: Trung vị số ngày giữa hai lần mua liên tiếp

In [5]:
orders_p1 = orders.copy()
orders_p1.head()

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign

In [6]:
orders_sorted = orders.sort_values(['customer_id', 'order_date'])
orders_sorted['days_diff'] = orders_sorted.groupby('customer_id')['order_date'].diff().dt.days

orders_sorted.head(10)

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,days_diff
4023,5280,2012-07-25,1,15201,delivered,cod,desktop,paid_search,NaN
143252,184922,2014-05-31,1,15201,returned,credit_card,mobile,referral,675.0
238890,308113,2015-07-31,1,15201,delivered,cod,mobile,paid_search,426.0
374571,483190,2017-04-23,1,15201,delivered,cod,mobile,paid_search,632.0
544446,702081,2020-02-24,1,15201,delivered,credit_card,mobile,organic_search,1037.0
586950,756884,2021-04-24,1,15201,paid,credit_card,desktop,social_media,425.0
91192,117673,2013-09-20,2,15201,delivered,paypal,mobile,social_media,NaN
97364,125576,2013-10-28,2,15201,cancelled,credit_card,desktop,direct,38.0
179458,231562,2014-11-13,2,15201,cancelled,bank_transfer,desktop,organic_search,381.0
632148,815219,2022-07-06,2,15201,delivered,apple_pay,mobile,paid_search,2792.0

In [7]:
inter_order_gaps = orders_sorted['days_diff'].median()
print(f"Question 1: {inter_order_gaps}")

Question 1: 144.0

* Q2: Phân khúc sản phẩm có tỷ suất lợi nhuận gộp trung bình cao nhất

In [8]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2412 entries, 0 to 2411
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    2412 non-null   int64
 1   product_name  2412 non-null   str
 2   category      2412 non-null   str
 3   segment       2412 non-null   str
 4   size          2412 non-null   str
 5   color         2412 non-null   str
 6   price         2412 non-null   float64
 7   cogs          2412 non-null   float64
dtypes: float64(2), int64(1), str(5)
memory usage: 150.9 KB

In [9]:
products.head()

,product_id,product_name,category,segment,size,color,price,cogs
0,536,SaigonFlex UC-01,Streetwear,Everyday,S,green,11059.650000,9704.842875
1,537,SaigonFlex UC-02,Streetwear,Everyday,M,silver,9523.076013,5393.870254
2,538,SaigonFlex UC-03,Streetwear,Everyday,L,pink,15951.633158,11371.919278
3,539,SaigonFlex UC-04,Streetwear,Everyday,XL,yellow,15753.717299,8573.172954
4,540,SaigonFlex UC-05,Streetwear,Everyday,S,red,15766.334536,14063.570406

In [10]:
products_p1 = products.copy()

products_p1['gross_margin_ratio'] = (products_p1['price'] - products_p1['cogs']) / products_p1['price']

products_p1.head()

,product_id,product_name,category,segment,size,color,price,cogs,gross_margin_ratio
0,536,SaigonFlex UC-01,Streetwear,Everyday,S,green,11059.650000,9704.842875,0.1225
1,537,SaigonFlex UC-02,Streetwear,Everyday,M,silver,9523.076013,5393.870254,0.4336
2,538,SaigonFlex UC-03,Streetwear,Everyday,L,pink,15951.633158,11371.919278,0.2871
3,539,SaigonFlex UC-04,Streetwear,Everyday,XL,yellow,15753.717299,8573.172954,0.4558
4,540,SaigonFlex UC-05,Streetwear,Everyday,S,red,15766.334536,14063.570406,0.1080

In [11]:
segment_margin = products_p1.groupby('segment')['gross_margin_ratio'].mean().sort_values(ascending=False)
print(segment_margin)

segment
Standard       0.313442
Premium        0.285377
All-weather    0.284176
Activewear     0.265600
Performance    0.263650
Balanced       0.258038
Trendy         0.240758
Everyday       0.236343
Name: gross_margin_ratio, dtype: float64

In [12]:
products_p1.describe()

        product_id         price          cogs  gross_margin_ratio
count  2412.000000   2412.000000   2412.000000         2412.000000
mean   1206.500000   4928.216231   3868.346732            0.265873
std     696.428747   4776.737669   3878.584151            0.151148
min       1.000000      9.056594      5.183829            0.050000
25%     603.750000     59.444924     35.066367            0.104000
50%    1206.500000   4399.605000   3184.934093            0.305850
75%    1809.250000   7720.513784   5864.916462            0.401166
max    2412.000000  40950.000000  38902.500000            0.499600

* Question 3: Xác định lý do trả hàng xuất hiện nhiều nhất cho danh mục Streetwear

In [13]:
returns_p1 = returns.copy()
returns_p1.head()

,return_id,order_id,product_id,return_date,return_reason,return_quantity,refund_amount
0,RET-000001,2,609,2012-07-25,late_delivery,6,52458.01
1,RET-000002,32,1862,2012-07-16,wrong_size,2,5141.37
2,RET-000003,35,2359,2012-07-16,wrong_size,1,5315.95
3,RET-000004,47,1449,2012-07-11,wrong_size,4,6493.75
4,RET-000005,47,1450,2012-07-25,wrong_size,1,1740.76

In [14]:
merged_q3 = pd.merge(returns_p1, products_p1[['product_id', 'category']], on='product_id', how='inner')

merged_q3.head()

,return_id,order_id,product_id,return_date,return_reason,return_quantity,refund_amount,category
0,RET-000001,2,609,2012-07-25,late_delivery,6,52458.01,Streetwear
1,RET-000002,32,1862,2012-07-16,wrong_size,2,5141.37,GenZ
2,RET-000003,35,2359,2012-07-16,wrong_size,1,5315.95,Streetwear
3,RET-000004,47,1449,2012-07-11,wrong_size,4,6493.75,Outdoor
4,RET-000005,47,1450,2012-07-25,wrong_size,1,1740.76,Outdoor

In [15]:
streetwear_returns = merged_q3[merged_q3['category'] == 'Streetwear']

top_reason = streetwear_returns['return_reason'].value_counts()
top_reason

return_reason
wrong_size          7626
defective           4330
not_as_described    3854
changed_mind        3830
late_delivery       2159
Name: count, dtype: int64

* Question 4: tỷ lệ thoát trung bình (bounce_rate) thấp nhất

In [16]:
web_traffic_p1 = web_traffic.copy()

web_traffic_p1.head()

,date,sessions,unique_visitors,page_views,bounce_rate,avg_session_duration_sec,traffic_source
0,2013-01-01,9760,7253,39093,0.00514,102.9,organic_search
1,2013-01-02,10456,8151,47611,0.00406,120.5,organic_search
2,2013-01-03,10076,7458,36963,0.00401,263.6,direct
3,2013-01-04,9973,8063,53078,0.00562,151.8,direct
4,2013-01-05,10223,7882,36790,0.00525,168.6,referral

In [17]:
source_bounce_rates = web_traffic_p1.groupby('traffic_source')['bounce_rate'].mean().sort_values(ascending=True)

source_bounce_rates

traffic_source
email_campaign    0.004458
social_media      0.004476
paid_search       0.004478
referral          0.004499
organic_search    0.004504
direct            0.004511
Name: bounce_rate, dtype: float64

* Question 5: Tỷ lệ phần trăm các dòng trong order_items.csv có áp dụng khuyến mãi

In [18]:
order_items_p1 = order_items.copy()

order_items_p1.head()

,order_id,product_id,quantity,unit_price,discount_amount,promo_id,promo_id_2
0,1,2400,7,1138.22,0.0,NaN,NaN
1,2,609,7,10166.25,0.0,NaN,NaN
2,3,396,3,11220.33,0.0,NaN,NaN
3,4,635,5,10639.25,0.0,NaN,NaN
4,6,1935,1,1597.84,0.0,NaN,NaN

In [19]:
order_items_p1.info()

<class 'pandas.DataFrame'>
RangeIndex: 714669 entries, 0 to 714668
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   order_id         714669 non-null  int64
 1   product_id       714669 non-null  int64
 2   quantity         714669 non-null  int64
 3   unit_price       714669 non-null  float64
 4   discount_amount  714669 non-null  float64
 5   promo_id         276316 non-null  str
 6   promo_id_2       206 non-null     str
dtypes: float64(2), int64(3), str(2)
memory usage: 38.2 MB

In [20]:
has_promo = order_items_p1['promo_id'].notna()

promo_percentage = has_promo.mean() * 100

print(f"Tỷ lệ phần trăm các dòng có áp dụng khuyến mãi: {promo_percentage:.2f}%")

Tỷ lệ phần trăm các dòng có áp dụng khuyến mãi: 38.66%

Question 6:

In [21]:
customers_p1 = customers.copy() 
customers_p1.head()

,customer_id,zip,city,signup_date,gender,age_group,acquisition_channel
0,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media
1,2,15201,Hai Phong,2013-12-27,Female,45-54,email_campaign
2,3,15201,Hai Phong,2018-07-24,Female,18-24,organic_search
3,4,15201,Hai Phong,2017-11-29,Male,35-44,referral
4,5,15201,Hai Phong,2022-09-23,Male,55+,organic_search

In [22]:
customers_p1.info()

<class 'pandas.DataFrame'>
RangeIndex: 121930 entries, 0 to 121929
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          121930 non-null  int64
 1   zip                  121930 non-null  int64
 2   city                 121930 non-null  str
 3   signup_date          121930 non-null  str
 4   gender               121930 non-null  str
 5   age_group            121930 non-null  str
 6   acquisition_channel  121930 non-null  str
dtypes: int64(2), str(5)
memory usage: 6.5 MB

In [23]:
customers_p1['age_group'].value_counts()

age_group
25-34    36342
35-44    31920
45-54    23172
18-24    17039
55+      13457
Name: count, dtype: int64

In [24]:
orders_p1.info()

<class 'pandas.DataFrame'>
RangeIndex: 646945 entries, 0 to 646944
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        646945 non-null  int64
 1   order_date      646945 non-null  datetime64[us]
 2   customer_id     646945 non-null  int64
 3   zip             646945 non-null  int64
 4   order_status    646945 non-null  str
 5   payment_method  646945 non-null  str
 6   device_type     646945 non-null  str
 7   order_source    646945 non-null  str
dtypes: datetime64[us](1), int64(3), str(4)
memory usage: 39.5 MB

In [25]:
merged_q6 = pd.merge(orders_p1, customers_p1, on='customer_id', how='inner')
merged_q6.info()

<class 'pandas.DataFrame'>
RangeIndex: 646945 entries, 0 to 646944
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             646945 non-null  int64
 1   order_date           646945 non-null  datetime64[us]
 2   customer_id          646945 non-null  int64
 3   zip_x                646945 non-null  int64
 4   order_status         646945 non-null  str
 5   payment_method       646945 non-null  str
 6   device_type          646945 non-null  str
 7   order_source         646945 non-null  str
 8   zip_y                646945 non-null  int64
 9   city                 646945 non-null  str
 10  signup_date          646945 non-null  str
 11  gender               646945 non-null  str
 12  age_group            646945 non-null  str
 13  acquisition_channel  646945 non-null  str
dtypes: datetime64[us](1), int64(4), str(9)
memory usage: 69.1 MB

In [26]:
orders_per_group = merged_q6.groupby('age_group')['order_id'].nunique()

customers_per_group = merged_q6.groupby('age_group')['customer_id'].nunique()

print("Số lượng đơn hàng theo nhóm tuổi:")
print(orders_per_group)
print("\nSố lượng khách hàng theo nhóm tuổi:")
print(customers_per_group)

Số lượng đơn hàng theo nhóm tuổi:
age_group
18-24     89057
25-34    190622
35-44    170368
45-54    124138
55+       72760
Name: order_id, dtype: int64

Số lượng khách hàng theo nhóm tuổi:
age_group
18-24    12599
25-34    26802
35-44    23642
45-54    17193
55+      10010
Name: customer_id, dtype: int64

In [27]:
total_customers = customers_p1['age_group'].value_counts()
avg_orders_per_customer_v1 = orders_per_group / total_customers

avg_orders_per_customer_v1.sort_values(ascending=False)

age_group
55+      5.406851
45-54    5.357241
35-44    5.337343
25-34    5.245226
18-24    5.226656
dtype: float64

In [28]:
avg_orders_per_customer = orders_per_group / customers_per_group

avg_orders_per_customer_sorted = avg_orders_per_customer.sort_values(ascending=False)

avg_orders_per_customer_sorted

age_group
55+      7.268731
45-54    7.220264
35-44    7.206159
25-34    7.112230
18-24    7.068577
dtype: float64

* Question 7:Vùng có tổng doanh thu cao nhất

In [29]:
orders_p1 = orders.copy()
customers_p1 = customers.copy()
geography_p1 = geography.copy()
order_items_p1 = order_items.copy()

In [30]:
#1 tổng doanh thu trên mỗi dòng đơn hàng
order_items_p1['line_revenue'] = order_items_p1['quantity'] * order_items_p1['unit_price']
order_items_p1.tail(10)

,order_id,product_id,quantity,unit_price,discount_amount,promo_id,promo_id_2,line_revenue
714659,834357,816,8,4468.76,0.0,NaN,NaN,35750.08
714660,834361,402,1,12793.37,0.0,NaN,NaN,12793.37
714661,834362,2124,6,10674.96,0.0,NaN,NaN,64049.76
714662,834367,1809,5,2747.70,0.0,NaN,NaN,13738.50
714663,834370,202,5,15994.24,0.0,NaN,NaN,79971.20
714664,834372,690,8,4473.92,0.0,NaN,NaN,35791.36
714665,834377,1995,7,5250.79,0.0,NaN,NaN,36755.53
714666,834387,2331,8,7389.06,0.0,NaN,NaN,59112.48
714667,834392,1115,5,4767.33,0.0,NaN,NaN,23836.65
714668,834397,1118,1,4716.75,0.0,NaN,NaN,4716.75

In [31]:
items_per_order = order_items.groupby('order_id').size()

items_per_order.value_counts()

1    580488
2     65256
3      1137
4        62
5         2
Name: count, dtype: int64

In [32]:
multi_orders = items_per_order[items_per_order > 1]

print(multi_orders.head())

order_id
8     2
20    2
47    2
48    2
72    2
dtype: int64

In [33]:
order_revenue = order_items_p1.groupby('order_id')['line_revenue'].sum().reset_index()
order_revenue[order_revenue['order_id'] == 8]

   order_id  line_revenue
6         8      16187.56

In [34]:
# Bước 3: Kết nối Đơn hàng -> Khách hàng -> Địa lý
# Đầu tiên kết nối doanh thu với thông tin đơn hàng để lấy zip khách hàng
temp_merged = pd.merge(order_revenue, orders_p1[['order_id', 'zip']], on='order_id', how='inner')
final_merged = pd.merge(temp_merged, geography_p1[['zip', 'region']], on='zip', how='inner')



region_revenue = final_merged.groupby('region')['line_revenue'].sum()
best_region = region_revenue.idxmax()
highest_revenue = region_revenue.max()

print("Tổng doanh thu theo từng vùng:")
print(region_revenue)
print(f"\nVùng tạo ra tổng doanh thu cao nhất là: {best_region}")

Tổng doanh thu theo từng vùng:
region
Central    4.941908e+09
East       7.637533e+09
West       3.851035e+09
Name: line_revenue, dtype: float64

Vùng tạo ra tổng doanh thu cao nhất là: East

* Question 8: trong order_status = 'cancelled'phương thức thanh toán nào được sử dụng nhiều nhất?

In [35]:
orders_p1 = orders.copy()
cancelled_orders = orders_p1[orders_p1['order_status'] == 'cancelled']
cancelled_orders['payment_method'].value_counts()

payment_method
credit_card      28452
cod              15468
paypal            7817
apple_pay         5190
bank_transfer     2535
Name: count, dtype: int64

* Question 9: kích thước nào có tỷ lệ trả hàng cao
nhất

In [36]:
order_items_p1 = order_items.copy()
returns_p1 = returns.copy()
products_p1 = products.copy()

In [37]:
#size trong order
items_with_size = pd.merge(order_items_p1, products_p1[['product_id', 'size']], on='product_id', how='inner')
size_order_counts = items_with_size['size'].value_counts()

size_order_counts

size
XL    193025
M     176428
L     173174
S     172042
Name: count, dtype: int64

In [38]:
# size trong return
returns_with_size = pd.merge(returns_p1, products_p1[['product_id', 'size']], on='product_id', how='inner')
size_return_counts = returns_with_size['size'].value_counts()

size_return_counts

size
XL    10655
M      9820
L      9741
S      9723
Name: count, dtype: int64

In [39]:
return_rate_by_size = size_return_counts / size_order_counts
print(return_rate_by_size.sort_values(ascending=False))

print(f"\nKích thước có tỷ lệ trả hàng cao nhất là: {return_rate_by_size.idxmax()}")

size
S     0.056515
L     0.056250
M     0.055660
XL    0.055200
Name: count, dtype: float64

Kích thước có tỷ lệ trả hàng cao nhất là: S

* Question 10: kế hoạch trả góp nào có giá trị thanh toán trung bình trên mỗi đơn hàng cao nhất?

In [40]:
payments_p1 = payments.copy()
payments_p1.head()

   order_id payment_method  payment_value  installments
0         1    credit_card        7967.54             3
1         2            cod       71163.75             1
2         3    credit_card       33660.99             3
3         4    credit_card       53196.25             3
4         6         paypal        1597.84             1

In [41]:
avg_payment_by_installment = payments_p1.groupby('installments')['payment_value'].mean().sort_values(ascending=False)

print("Giá trị thanh toán trung bình theo số kỳ trả góp:")
print(avg_payment_by_installment)

Giá trị thanh toán trung bình theo số kỳ trả góp:
installments
6     24446.654403
3     24399.635486
12    24245.772694
1     24113.274166
2       708.473729
Name: payment_value, dtype: float64